apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
data:
  mosquitto.conf: |
{{ .Values.mosquittoConf | indent 4 }}
{{ if .Values.caCrt }}
  ca.crt: |
{{ .Values.caCrt | indent 4 }}
{{ end }}
{{ if .Values.clientCrt }}
  client.crt: |
{{ .Values.clientCrt | indent 4 }}
{{ end }}
