{{ if .Values.clientKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
data:
  client.key: {{ .Values.clientKey | b64enc }}
{{ end }}
